SELECT * FROM BOARD ORDER BY BOARD_DATE DESC;

SELECT * FROM BOARD_COMMENT WHERE BOARD_REF=31 START WITH BOARD_COMMENT_LEVEL=1 CONNECT BY PRIOR BOARD_COMMENT_NO=BOARD_COMMENT_REF;

SELECT * FROM MEMBER;